version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
      - image: amazoncorretto:17-alpine
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: sleep
          command: sleep 20

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
